-- db/seeds/municipal_boundaries.sql — Seed municipal boundaries
--
-- Empty by design. The Dallas "pilot envelope" placeholder (a coarse,
-- hand-drawn rectangle, never production-grade city limits) was dropped by
-- migration 046_drop_dallas_pilot_boundary.sql — nationwide jurisdiction
-- resolution now falls back to the Census Bureau's own `geographies` lookup
-- (rag/jurisdiction_resolver.py::resolve_jurisdiction_for_point) instead of
-- requiring a locally-loaded polygon, and a stale placeholder would have
-- silently shadowed that for every Dallas address.
--
-- Add rows here only for real, sourced boundary data via
-- scripts/load_gis_boundaries.py — this table is now scoped to a small
-- number of cities where the team wants precision beyond Census's place
-- boundary (ETJs, annexation corrections), not a general resolution
-- mechanism.
